# NUMPY(NUMERICAL PYTHON)

# ARRAY

An array is a collection of items stored at contiguous memory location, each identified by at least one array index or key.
    
The idea is to store multiple items of the same type together.

# NUMPY TUTORIAL

Numpy is python package. It stands for"Numerical Python". It is a Library consisting of multidimensional array objects and a collection of routines for processing of array

In [8]:
import numpy

In [9]:
numpy.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [10]:
numpy.array([11,12,13,14,15])

array([11, 12, 13, 14, 15])

In [11]:
a = numpy.array([10,20,30,40])

In [12]:
a

array([10, 20, 30, 40])

In [13]:
a.size

4

In [7]:
# by default int32

a.dtype


dtype('int32')

In [1]:
import numpy as np    # np is alternative name/alias

In [14]:
a1=np.array([12,13,14,15,2,4,56,8,9,1,11])

In [15]:
a1

array([12, 13, 14, 15,  2,  4, 56,  8,  9,  1, 11])

In [25]:
a1.min()

1

In [17]:
a1.max()

56

In [19]:
a2=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,18,20], dtype='int')

In [20]:
a2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 18, 20])

In [21]:
a2.dtype

dtype('int32')

In [26]:
# gives the no. of bytes/memory occupied by each element

a2.itemsize

4

In [27]:
# gives the count of number of element

a2.size

17

In [28]:
a3=np.array([55,44,89,22,65], dtype='int64')

In [29]:
a3

array([55, 44, 89, 22, 65], dtype=int64)

In [30]:
a3.size

5

In [31]:
a3.itemsize

8

In [32]:
a3.dtype #gives the data type

dtype('int64')

In [35]:
a4=np.array([55,44,89,22,65], dtype='float')
a4


array([55., 44., 89., 22., 65.])

In [36]:
a4.size


5

In [37]:
a4.itemsize  # by default float is 8 bytes/64 bit

8

In [38]:
a4.dtype

dtype('float64')

In [39]:
# gives shape in dimension: rows and column.

a4.shape


(5,)

2 Dimenstional Array(rows and column)

In [1]:
import numpy as np

In [2]:
b=np.array([[1,2], [3,4]])

In [3]:
b

array([[1, 2],
       [3, 4]])

In [4]:
b.ndim   # stands for row and column

2

In [5]:
b.shape  # 2 rows and 2 column

(2, 2)

3 rows and 2 columns

In [6]:
c=np.array([[20,30],[40,50],[60,70]])

In [7]:
c

array([[20, 30],
       [40, 50],
       [60, 70]])

In [8]:
c.ndim

2

In [9]:
c.shape

(3, 2)

rows and columns means 2 dimenstion

# Reshape

In [10]:
c.reshape(2,3) # 2 rows and 3 column

array([[20, 30, 40],
       [50, 60, 70]])

2 rows and 3 columns 

In [11]:
d=np.array([[11,12,13],[14,15,16]])

In [12]:
d

array([[11, 12, 13],
       [14, 15, 16]])

In [13]:
d.shape

(2, 3)

In [14]:
d.reshape(3,2)

array([[11, 12],
       [13, 14],
       [15, 16]])

4 rows and 4 column

In [15]:
e=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [16]:
e

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [17]:
e.shape

(4, 4)

Array Range

In [18]:
x=np.arange(15)

In [19]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
e1=x.reshape(3,5)

In [21]:
e1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [22]:
ab=np.arange(35).reshape(5,7)

In [23]:
ab

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [24]:
ab.shape

(5, 7)

In [25]:
ab.ndim

2

In [26]:
type(ab)

numpy.ndarray

In [27]:
import numpy as np

In [28]:
bc=np.array([[1.5,2,3],[4,5,6]], dtype='float32')

In [29]:
bc

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]], dtype=float32)

In [30]:
cd=np.array([[34,78,89],[22,33,77]])

In [31]:
cd

array([[34, 78, 89],
       [22, 33, 77]])

In [32]:
# ravel operation where you can convert one numpy array into a single row. i.e ravel

print(cd.ravel())

[34 78 89 22 33 77]


In [33]:
abc=np.array([[1.5,2,3],[4,5,6]], dtype='int32')

In [34]:
abc

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [38]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [39]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
# start, end skip or jump

np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [43]:
ba=np.arange(12).reshape(4,3)
ba

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

# Broadcasting in numpy

The term broadcasting describe how numpy treats array with different shape during arithmetic operations. Subject to certain constraints, the similar array is 'Broadcast' across the large array so that they have compatible shapes.
Broadcasting provides a means of vectorizing array operations.

In [1]:
import numpy as np

In [2]:
x1=np.array([1.0,2.0,3.0])
x2=np.array([2.0,2.0,2.0])
x1*x2

array([2., 4., 6.])

In [4]:
x3=np.array([1.0,2.0,3.0])
x4=2.0
x3*x4

array([2., 4., 6.])

In [6]:
x5=np.array([20,30,40,50])
x6=np.arange(4)
print(x5)
print(x6)

[20 30 40 50]
[0 1 2 3]


In [7]:
abc=x5-x6
print(abc)

[20 29 38 47]


In [8]:

x6**2

array([0, 1, 4, 9], dtype=int32)

In [9]:
x5**2

array([ 400,  900, 1600, 2500], dtype=int32)

In [10]:
# random means any system generated data

z1=np.random.random([2,3])

In [11]:
z1

array([[0.48903676, 0.52648722, 0.81844669],
       [0.31102497, 0.98017973, 0.8459029 ]])

In [12]:
y=x5+x6

In [13]:
y

array([20, 31, 42, 53])

In [17]:
y3=np.ones([2,3])
y3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
y4=z1+y3
y4

array([[2., 2., 2.],
       [2., 2., 2.]])

# UNIVERSAL FUNCTION

In [20]:
y5=np.arange(3)

In [21]:
y5

array([0, 1, 2])

In [22]:
# exponent

np.exp(y5)

array([1.        , 2.71828183, 7.3890561 ])

In [23]:
np.sqrt(y5)

array([0.        , 1.        , 1.41421356])

In [24]:
y6=np.array([4,5,6])
y6

array([4, 5, 6])

In [25]:
np.add(y5,y6)

array([4, 6, 8])

# INDEXING, SLICING AND ITERATING

In [26]:
import numpy as np

In [27]:
a=np.arange(10)

In [28]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
a[2]

2

In [30]:
a[2:5]

array([2, 3, 4])

In [31]:
a[-1]

9

In [32]:
a[-2]

8

In [34]:
a[-3]

7

In [35]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
a[-4:]

array([6, 7, 8, 9])

In [37]:
a[-4:-2]

array([6, 7])

In [38]:
ab=np.arange(20)
ab

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [39]:
ab[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [40]:
bc=np.array([np.nan, 1,2,3,np.nan,6,7,8])  # nan---> missing data
bc

array([nan,  1.,  2.,  3., nan,  6.,  7.,  8.])


The random module provides nice function to generate random nunbers(and also statistical distributions)of any given shape.
Rand function will generate any number b/w 0 and 1

In [41]:
np.random.rand(2,2)  # uniform distributions-------> similar like random

array([[0.46157553, 0.53144248],
       [0.27367581, 0.44567155]])



Randn will generate any number for normal distribution in the given dimention format

In [42]:
np.random.randn(2,3)

array([[-1.25711164,  0.97707653,  0.07506362],
       [-1.34710798, -0.35491985,  1.34270522]])

random, (0--1)
       <------------> similar
rand, (0--1)

randn---> gives some (+ve) data or some (-ve) data


# DONE WITH NUMPY

 ------ END----- 